name: connectivity_monitor_plus
description: "Flutter package for real-time network status and internet access checks by pinging a URL. Detects connectivity changes instantly."
version: 0.0.1
homepage: https://github.com/afaq3522/connectivity_monitor_plus
repository: https://github.com/afaq3522/connectivity_monitor_plus
issue_tracker: https://github.com/afaq3522/connectivity_monitor_plus/issues
documentation: https://github.com/afaq3522/connectivity_monitor_plus#readme
license: MIT

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^6.1.4
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

topics:
  - connectivity
  - internet
  - flutter
  - network
  - utility

flutter:
