name: Connectivity Monitor CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    name: Analyze & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Check formatting
        run: dart format . --set-exit-if-changed

      - name: Analyze code
        run: flutter analyze

      - name: Run unit tests
        run: flutter test

      # Optional: Check example project builds (helps pub points)
      - name: Check example project builds
        run: |
          cd example
          flutter pub get
          flutter analyze
          flutter test
